### ISSUE TITLE
swagger json file

### ISSUE THREAD

**Issue by jbrauchler** [fsbahman/apidoc-swagger#8]
Where should the swagger json file be appearing in our folder? I am not seeing it, just want to make sure I get the right idea and am able to be successful with it. Any help would be great.

**Comment by fsbahman** [comment]
Hi, if you use it via command like this:
apidoc-swagger -i example/ -o doc/ 
then the -o is to identify output folder where the swagger.json should appear.

**Comment by jbrauchler** [comment]
I realized it was running apidoc rather than apidoc-swagger and that was why the swagger.json file wasn't appearing.
