### ISSUE TITLE
Any news here? Especially for a new npm version?

### ISSUE THREAD

**Issue by alqu** [fsbahman/apidoc-swagger#9]
See title.

I myself fixed the "multiple methods under one path" issue... only to find out, that it has already been fixed in the current master.

Please release a fresh version to npm. Thanks.

**Comment by fsbahman** [comment]
Hi, the npm packages are updated, please have a look and let me know if anything.

**Comment by alqu** [comment]
Cool, works perfect now!

Thanks a lot.
